### ISSUE TITLE
can't get module to work with omeka s

### ISSUE THREAD

**Issue by oupala** [Daniel-KM/Omeka-S-module-Folksonomy#3]
I can't get module to work with omeka s.

- omeka s is version 1.0.0 or 1.0.1
- folksonomy is version 3.3.5

I can enable the module without any error.  But I can't then consult the pages `/admin/tag` or `/admin/tagging` nor I can get the `/admin/item` page. Consulting those page display an error message: **Omeka S rencontre une erreur** (in french).

Any clue to diagnose the bug is welcomed.

**Comment by oupala** [comment]
I get the same problem with version 1.0.1 of omeka s.

Could it be related to permissions?

**Comment by Daniel-KM** [comment]
Yes i see some issues too, but it works in my case because of another module. So I ll release a full clean release next week.

**Comment by oupala** [comment]
In my case, I do not have any other plugin enabled at this moment.

I'll be please to test your next release next week.

**Comment by Daniel-KM** [comment]
I updated the module, but I didn't find your strange bug. Have you some log (change the first line of .htaccess into `SetEnv APPLICATION_ENV "development"`) temporarily.

**Comment by oupala** [comment]
I can't see any new version of your module (the last one is 3.3.5).

I thought you would publish *a full clean release [last] week*. Wouldn't you ?

**Comment by oupala** [comment]
Wow, debugging was straight forward:

```
 Doctrine\DBAL\Exception\TableNotFoundException
An exception occurred while executing 'SELECT t0_.id AS id_0, t0_.status AS status_1, t0_.created AS created_2, t0_.modified AS modified_3, t0_.tag_id AS tag_id_4, t0_.resource_id AS resource_id_5, t0_.owner_id AS owner_id_6 FROM tagging t0_ WHERE t0_.resource_id = ? GROUP BY t0_.id ORDER BY t0_.id ASC' with params [1]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dev.tagging' doesn't exist

Détails :

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dev.tagging' doesn't exist in /srv/data/web/vhosts/dev.osterlind.fr/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
̀```

How should this table created?

**Comment by Daniel-KM** [comment]
The module creates two tables during install tag and tagging. I don't understand why this is not the case here. Could you go to the module page and uninstall / install it?

**Comment by Daniel-KM** [comment]
Last commit is 5ff3f48.

**Comment by Daniel-KM** [comment]
I published version 3.3.6.

**Comment by oupala** [comment]
I can disable the module with success, and then reinstall it with success also.

But I get the same error while going to the Content page, or on the Folksonomy module page.

I'll try to update the module version to 3.3.6.

**Comment by oupala** [comment]
I've updated to version 3.3.6 and the upgrade went well. But I still have the same behaviour while trying to use the module.

I think it might be a permission related issue.

Can you tell me what permissions does the database user has to have on the database?

**Comment by Daniel-KM** [comment]
The two tables are created at the same time with the same command: https://github.com/Daniel-KM/Omeka-S-module-Folksonomy/blob/9fc8e5dbd3a69e8500d5804dd4b2e235cfa6ad1d/Module.php#L52. So, it means that the first part of the sql command succeeded, but not the second, that contains some constraints failed silently. What is your version of mysql / mariadb ?

**Comment by oupala** [comment]
I'm using Percona Server, version 7.18-16-log - Percona.

I think your install script would be more robust if you check the return code of the sql statement execution:

https://github.com/Daniel-KM/Omeka-S-module-Folksonomy/blob/9fc8e5dbd3a69e8500d5804dd4b2e235cfa6ad1d/Module.php#L79

And if you can display the error when it occurs (in dev mode only), it would be an easy way to debug that.

**Comment by oupala** [comment]
It seems that `reference` permission is needed, this should be mentioned in the documentation. Each mandatory permission should be mentioned in the documentation.

I can't make the script create and delete `tag` and `tagging` tables. I think error handling could really improve the script reliability.

**Comment by Daniel-KM** [comment]
The script is provided automatically by Doctrine and a similar install task is found in many of the official modules. I don't know anything about the specificities of Percona, that is not supported by Omeka S. Normally Percona is compatible, but the management of permissions are always complex. So I don't know what I can do.

**Comment by oupala** [comment]
The problem is that an error seems to occurs and is not catched by the script.

Do you mean that Doctrine prevent from catching the error?

If it is, it means that Doctrine has a real weakness in the way it handle errors.

**Comment by Daniel-KM** [comment]
The install query is provided by Doctrine. I can't modify it, else my database won't be sync with my module. I can add a check for the issue, but this will not help you, you know where the error occurs.

All the servers I manage works fine with this install process. You can try it on my demo server https://demo.sempiternelia.net/omeka-s (in French only, sorry), that uses a standard web provider.

What is the answer of Percona when you request the query directly (via adminer, phpmyadmin or cli)? Normally, it should explain the error or give an error code.

**Comment by oupala** [comment]
> I can add a check for the issue, but this will not help you, you know where the error occurs.

It **would** help me. The information that is important to me is not where the error occurs, it is the error itself, its message and its error code.

I tried to execute the statement via phpMyAdmin, but the problem is that I'm using the root user instead of the application user. And I have no possibility to use another user as root with phpMyAdmin. It is a constraint from my hoster.

**Comment by Daniel-KM** [comment]
I added a check in order to log the error from the sql server.

**Comment by oupala** [comment]
I installed Folksonomy v3.3.7.

Where can I find the log from the install or the uninstall?

**Comment by oupala** [comment]
Ah, it seems that the commit that adds a log is not yet published in a release...

**Comment by Daniel-KM** [comment]
I replaced the 3.3.7 with the last commit.

**Comment by oupala** [comment]
Where should an error be displayed or logged?

I can install and uninstall the module, and I can't see any error.

**Comment by Daniel-KM** [comment]
If you can install and uninstall, it means that there is no error. The errors are displayed inside the file `logs/application.log` if they are enabled (add `SetEnv APPLICATION_ENV "development"` in `.htaccess`, and/or set it in `config/local.config.php`.
To know if it is installed without error, go to an item in admin board and add a tag.

**Comment by oupala** [comment]
In fact, I really think it doesn't work.

When uninstalling the module, I can still see the `tag` and `tagging` tables, there are not dropped. And as the tables are not dropped on uninstall, there is no problem if the tables are not created on install, as they have not been dropped.

Application is in *development* mode by the use of an htaccess directive. But `application.log` and `sql.log` are empty.

I really don't understand why installing and uninstalling the module does not create and drop tables.

**Comment by Daniel-KM** [comment]
It means that the install process worked last time, but not the uninstall process.
It means that queries that contains multiple queries cannot be executed on your system (only the first one).
I updated the install and uninstall process in order to divide queries (still 3.3.7). 
Nevertheless, to have multiple queries for an install or uninstall is frequent. And it can be the case anywhere in a module (rare). So I will fix only install/uninstall on my modules.

**Comment by oupala** [comment]
I tested the same process on another environment and it worked: the `tag` and `tagging` tables were both created on module install, and deleted on module uninstall.

I'll have to check why it is not working this way on my previous environment. Thanks though for having added logs and error catching.
